### PR TITLE
Only add user if it has not been added already

### PR DESCRIPTION
**Pull request by richford**

### CODE REVIEW

**Comment by richford** [comment]
@arokem, I added a section that only add the home directory if it doesn't exist already. Could you test drive this on the use case you showed me this morning (or neurodocker)?

**Comment by richford** [comment]
@arokem, did you get a chance to test drive this?

**Comment by arokem** [comment]
Sorry - not yet...

We ended up hacking our way round this. I'll give it a try later today.

**Comment by arokem** [comment]
OK - we've tried this out, by installing this branch and removing our hacks. It seems to work!

**Comment by richford** [comment]
Great! I'll go ahead and merge then.

**Pull request merged**
