### PR TITLE
Fix get_user() function to handle root

### LINKED ISSUE #202: ParamValidationError when calling cloudknot.Knot()
Hi,
I've been trying to get the 00_random_matrix_vector_multiply example running, but encountered an error when calling `knot = ck.Knot(name='random-mv-prod', base_image="python:3.7", func=random_mv_prod, memory=128, retries=3)`. The error message is as follows,
```
---------------------------------------------------------------------------
ParamValidationError                      Traceback (most recent call last)
<ipython-input-3-f1bddcf6de42> in <module>
----> 1 knot = ck.Knot(name='random-mv-prod', base_image="python:3.7", func=random_mv_prod, memory=128, retries=3)

~/anaconda3/lib/python3.7/site-packages/cloudknot-0.3.1-py3.7.egg/cloudknot/cloudknot.py in __init__(self, name, pars, pars_policies, docker_image, base_image, func, image_script_path, image_work_dir, image_github_installs, username, repo_name, image_tags, job_definition_name, job_def_vcpus, memory, retries, compute_environment_name, instance_types, resource_type, min_vcpus, max_vcpus, desired_vcpus, image_id, ec2_key_pair, bid_percentage, job_queue_name, priority)
   1480             }
   1481 
-> 1482             self._pars, pars_cleanup = futures["pars"].result()
   1483 
   1484             self._docker_image, self._docker_repo, repo_cleanup = futures[

~/anaconda3/lib/python3.7/concurrent/futures/_base.py in result(self, timeout)
    430                 raise CancelledError()
    431             elif self._state == FINISHED:
--> 432                 return self.__get_result()
    433             else:
    434                 raise TimeoutError()

~/anaconda3/lib/python3.7/concurrent/futures/_base.py in __get_result(self)
    382     def __get_result(self):
    383         if self._exception:
--> 384             raise self._exception
    385         else:
    386             return self._result

~/anaconda3/lib/python3.7/concurrent/futures/thread.py in run(self)
     55 
     56         try:
---> 57             result = self.fn(*self.args, **self.kwargs)
     58         except BaseException as exc:
     59             self.future.set_exception(exc)

~/anaconda3/lib/python3.7/site-packages/cloudknot-0.3.1-py3.7.egg/cloudknot/cloudknot.py in set_pars(knot_name, input_pars, pars_policies_)
   1362                 else:
   1363                     try:
-> 1364                         pars_ = Pars(name=knot_name, policies=pars_policies_)
   1365                     except aws.CannotCreateResourceException:
   1366                         pars_ = Pars(

~/anaconda3/lib/python3.7/site-packages/cloudknot-0.3.1-py3.7.egg/cloudknot/cloudknot.py in __init__(self, name, batch_service_role_name, ecs_instance_role_name, spot_fleet_role_name, policies, use_default_vpc, ipv4_cidr, instance_tenancy)
    305                 policy_arns += [aws_policies[policy] for policy in policy_names]
    306 
--> 307             s3_params = aws.get_s3_params()
    308             policy_list = [s3_params.policy_arn] + [policy for policy in policy_arns]
    309             policies = ",".join(policy_list)

~/anaconda3/lib/python3.7/site-packages/cloudknot-0.3.1-py3.7.egg/cloudknot/aws/base_classes.py in get_s3_params()
    165         # Use set_s3_params to check for name availability
    166         # and write to config file
--> 167         set_s3_params(bucket=bucket, policy=policy, sse=sse)
    168 
    169         if policy is None:

~/anaconda3/lib/python3.7/site-packages/cloudknot-0.3.1-py3.7.egg/cloudknot/aws/base_classes.py in set_s3_params(bucket, policy, sse)
    256         try:
    257             if get_region() == "us-east-1":
--> 258                 clients["s3"].create_bucket(Bucket=bucket)
    259             else:
    260                 clients["s3"].create_bucket(

~/anaconda3/lib/python3.7/site-packages/botocore-1.13.39-py3.7.egg/botocore/client.py in _api_call(self, *args, **kwargs)
    270                     "%s() only accepts keyword arguments." % py_operation_name)
    271             # The "self" in this scope is referring to the BaseClient.
--> 272             return self._make_api_call(operation_name, kwargs)
    273 
    274         _api_call.__name__ = str(py_operation_name)

~/anaconda3/lib/python3.7/site-packages/botocore-1.13.39-py3.7.egg/botocore/client.py in _make_api_call(self, operation_name, api_params)
    547         }
    548         request_dict = self._convert_to_request_dict(
--> 549             api_params, operation_model, context=request_context)
    550 
    551         service_id = self._service_model.service_id.hyphenize()

~/anaconda3/lib/python3.7/site-packages/botocore-1.13.39-py3.7.egg/botocore/client.py in _convert_to_request_dict(self, api_params, operation_model, context)
    593                                  context=None):
    594         api_params = self._emit_api_params(
--> 595             api_params, operation_model, context)
    596         request_dict = self._serializer.serialize_to_request(
    597             api_params, operation_model)

~/anaconda3/lib/python3.7/site-packages/botocore-1.13.39-py3.7.egg/botocore/client.py in _emit_api_params(self, api_params, operation_model, context)
    625                 service_id=service_id,
    626                 operation_name=operation_name),
--> 627             params=api_params, model=operation_model, context=context)
    628         return api_params
    629 

~/anaconda3/lib/python3.7/site-packages/botocore-1.13.39-py3.7.egg/botocore/hooks.py in emit(self, event_name, **kwargs)
    354     def emit(self, event_name, **kwargs):
    355         aliased_event_name = self._alias_event_name(event_name)
--> 356         return self._emitter.emit(aliased_event_name, **kwargs)
    357 
    358     def emit_until_response(self, event_name, **kwargs):

~/anaconda3/lib/python3.7/site-packages/botocore-1.13.39-py3.7.egg/botocore/hooks.py in emit(self, event_name, **kwargs)
    226                  handlers.
    227         """
--> 228         return self._emit(event_name, kwargs)
    229 
    230     def emit_until_response(self, event_name, **kwargs):

~/anaconda3/lib/python3.7/site-packages/botocore-1.13.39-py3.7.egg/botocore/hooks.py in _emit(self, event_name, kwargs, stop_on_response)
    209         for handler in handlers_to_call:
    210             logger.debug('Event %s: calling handler %s', event_name, handler)
--> 211             response = handler(**kwargs)
    212             responses.append((handler, response))
    213             if stop_on_response and response is not None:

~/anaconda3/lib/python3.7/site-packages/botocore-1.13.39-py3.7.egg/botocore/handlers.py in validate_bucket_name(params, **kwargs)
    226             'the regex "%s" or be an ARN matching the regex "%s"' % (
    227                 bucket, VALID_BUCKET.pattern, VALID_S3_ARN.pattern))
--> 228         raise ParamValidationError(report=error_msg)
    229 
    230 

ParamValidationError: Parameter validation failed:
Invalid bucket name "cloudknot-arn:aws:iam::168469671006:root-798684f0-d7f7-4323-b87c-adeab2d6d1d8": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:s3:[a-z\-0-9]+:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-]{1,63}$"
```

I have no idea how bucket name "cloudknot-arn:aws:iam::168469671006:root-798684f0-d7f7-4323-b87c-adeab2d6d1d8" is generated (obviously 168469671006 is my aws account number). I suspect that some configuration of S3 is missing here, because in my ~/.aws/config file are only region=us-east-1, output=json, AWS_ACCESS_KEY_ID=XXXXXXXX, AWS_SECRET_ACCESS_KEY=YYYYYYYY.

I am running it on MacOS 10.15 with Docker Desktop 2.1.0.5. I installed cloudknot from the current master branch and ran `cloudknot configure` with my AWS key id and access key before I tried the example.

### PR DESCRIPTION
**Pull request by richford**
Resolves #202

### CODE REVIEW

**Comment by richford** [comment]
@hedongn1, could you please test this out to confirm that it resolves your issue in #202?

**Comment by richford** [comment]
Hmm, @hedongn1, the travis-ci hints that this might not work for you either. Hold on a bit on testing, please.

**Comment by hedongn1** [comment]
Yeah, I just tried, and `user_info.get("Arn")` returns `None`.

**Comment by richford** [comment]
Okay, I just pushed another fix. That works on my end but I'm not sure if it will work in your case. Could you test it again please?

**Comment by hedongn1** [comment]
Hi @richford, it worked! Thank you so much for your help!

**Comment by richford** [comment]
@hedongn1, good to hear! I'll wait until the CI passes and then merge.

**Pull request merged**
