### PR TITLE
Example process mri data

### PR DESCRIPTION
**Pull request by arokem**
An example with a realistic analysis on MRI data.

Still need to check this works as expected.

### CODE REVIEW

**Comment by arokem** [comment]
The example now works, and is ready for a review. 

Do you understand why Travis is failing?

**Comment by richford** [comment]
I don't completely understand why. Can you run this command locally: `ck.set_s3_bucket('cloudknot-travis-build-45814031-351c-4b27-9a40-672c971f7e83')`

**Comment by richford** [comment]
BTW, that is just to diagnose the travis build errors. Afterward, you should delete the `s3-bucket = ` line under the `[aws]` section in your cloudknot config file.

**Comment by richford** [comment]
In the travis builds, we set the AWS credentials using environment variables. Is it possible that travis builds for commits that you authored or committed don't use the same environment variables?

**Comment by richford** [comment]
Oh I see:

```
Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions
```

**Comment by richford** [comment]
We'll have to think more about how to deal with this.

**Comment by richford** [comment]
Merging since it only adds an example file, there is no way it can affect the travis-ci builds.

**Pull request merged**
